testnet=1
server=1
txindex=1

[test]
rpcuser=bitcoin
rpcpassword=bitcoin
rpcallowip=0.0.0.0/0
rpcbind=0.0.0.0
rpcport=18332
zmqpubrawblock=tcp://0.0.0.0:28332
zmqpubrawtx=tcp://0.0.0.0:28333
port=18333
